project_id = "ksnjypvnnrynsuuvnqre"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.automation-processor]
verify_jwt = false

[functions.n8n-trigger]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.n8n-status]
verify_jwt = false

[functions.trigger-n8n-workflow]
verify_jwt = false

[functions.calculator-events]
verify_jwt = false

[functions.n8n-status-update]
verify_jwt = false

[functions.twenty-crm-webhook]
verify_jwt = false

[functions.smartlead-engagement]
verify_jwt = false

[functions.integration-health]
verify_jwt = false

[functions.twenty-crm-integration]
verify_jwt = false

[functions.create-crm-person]
verify_jwt = false

[functions.create-crm-company]
verify_jwt = false

[functions.create-crm-opportunity]
verify_jwt = false