// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odgibblnukklsehfwjky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZ2liYmxudWtrbHNlaGZ3amt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzUxODUsImV4cCI6MjA2ODU1MTE4NX0.fk7EcH_nDJ1jOnmPJ5ZWFlbOtKqrTKMVmJ4KMOyTV3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Force a rebuild to regenerate types after schema changes
console.log('Supabase client initialized with schema version:', Date.now());