// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksnjypvnnrynsuuvnqre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzbmp5cHZubnJ5bnN1dXZucXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTIzMjQsImV4cCI6MjA2NzM4ODMyNH0.pzwWDGsjIQQVehQP-dob4MgHdyVJAlkZ7uivRzfPJVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});